yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('group/', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        help_text='Введите дату',
        auto_now_add=True
    )
    exch_date = models.DateTimeField(
        verbose_name='Дата последнего редактирования',
        help_text='Введите дату',
        auto_now=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите автора'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Выберите картинку для красоты'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост для комментирования',
        help_text='К какому посту вы хотите сделать комментарий?'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
        help_text='Выберите автора комментария',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания комментария',
        help_text='Введите дату',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:30]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Выберите пользователя, который хочет подписаться на кого-то'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Избранный автор',
        help_text='Выберите автора, на которого вы хотите подписаться'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]

    def save(self, *args, **kwargs):
        if self.user == self.author:
            return
        else:
            super().save(*args, **kwargs)

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if data.strip() == '1':
            error_explanation = 'Вы должны ввести какой-нибудь умный мысль!!!'
            raise forms.ValidationError(error_explanation)
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import page_from_paginator


def index(request):
    template = 'posts/index.html'
    page_obj = page_from_paginator(Post.objects.select_related(
        'author', 'group').all(), request.GET.get('page'))
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    page_obj = page_from_paginator(
        group.posts.select_related(
            'author', 'group').all(), request.GET.get('page'))
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    page_obj = page_from_paginator(
        author.posts.select_related(
            'author', 'group').all(), request.GET.get('page'))
    if request.user.is_authenticated:
        current_user = get_object_or_404(User, username=request.user)
        following = Follow.objects.filter(
            user=current_user, author=author).exists()
    else:
        following = False
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form_for_comment = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form_for_comment': form_for_comment,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post_save = form.save(commit=False)
        post_save.author = request.user
        post_save.save()
        return redirect(reverse('post:profile', args=[request.user.username]))
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect(reverse('post:post_detail', args=[post_id]))
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect(reverse('post:post_detail', args=[post_id]))
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('post:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    current_user = get_object_or_404(User, username=request.user)
    list_posts_selected_authors = Post.objects.select_related(
        'author', 'group').filter(author__following__user=current_user).all()
    page_obj = page_from_paginator(
        list_posts_selected_authors, request.GET.get('page'))
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # subscribe to author "username"
    current_user = get_object_or_404(User, username=request.user.username)
    author = get_object_or_404(User, username=username)
    Follow.objects.get_or_create(user=current_user, author=author)
    return redirect('post:follow_index')


@login_required
def profile_unfollow(request, username):
    # Dislike, unsubscribe from author "username"
    current_user = get_object_or_404(User, username=request.user.username)
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=current_user, author=author).delete()
    return redirect('post:follow_index')

yatube/templates/posts/includes/comments.html
{% for comment in comments %}
    <div class="media mb-4">
    <div class="media-body">
        <h5 class="mt-0">
        <a href="{% url 'post:profile' comment.author.username %}">
            {{ comment.author.username }}
        </a>
        </h5>
        <p>
        {{ comment.text }}
        </p>
        </div>
    </div>
{% endfor %}

yatube/templates/posts/includes/form_create_comments.html
{% load user_filters %}
{% if user.is_authenticated %}
    <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
        <form method="post" action="{% url 'post:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
            {{ form_for_comment.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
    </div>
{% endif %}

yatube/templates/posts/includes/list_posts.html
{% load thumbnail %}
{% for post in page_obj %}
  <div class="row">
    <article class="col-5">
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          {% url 'post:profile' post.author.username as url_temp %}
          <a href="{{ url_temp }}">все посты пользователя</a>            
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li>
          Дата редактирования: {{ post.exch_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaks }}</p>
      {% url 'post:post_detail' post.pk as url_temp %}
      <a href="{{ url_temp }}">подробная информация</a>
      {% if post.group %}
        {% url 'post:group_list' post.group.slug as url_temp %}
        <br><a href="{{ url_temp }}">Все записи группы: <strong>{{ post.group.title }}</strong></a>
      {% else %}
        <br><strong>Пост не принадлежит никакой группе</strong>          
      {% endif %}
    </article>
    <div class="col-7">
      {% thumbnail post.image "x200" as im %}
        <img src="{{ im.url }}">
      {% endthumbnail %}
    </div>
  </div>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/panel_follow.html
{% if user.is_authenticated and author.username != user.get_username %}
  {% if following %}
    <a
      class="btn btn-lg btn-secondary"
      href="{% url 'post:profile_unfollow' author.username %}" role="button"
    >
    Отписаться
    </a>
{% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'post:profile_follow' author.username %}" role="button"
    >
    Подписаться
    </a>
  {% endif %}
{% endif %}

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'post:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'post:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}