yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('group/', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


# creating a custom class for the registration form
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('post:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  {% with card_header='Выход' card_body='Вы вышли из своей учётной записи. Ждём вас снова!' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}

{% block content %}
{{ login_url }}
  {% with card_header='Войти на сайт' %}
  {% with text_submit='Войти' %}
  {% url 'users:password_reset' as add_link_adress %}
  {% with add_link_text='Забыли пароль?' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
  {% endwith %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_change.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
  {% with card_header='Изменение пароля' text_submit='Измененить' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль успешно изменен{% endblock %}

{% block content %}
  {% with card_header='Пароль успешно изменен' card_body='Ваш пароль был изменен!' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_complete copy.html
{% extends "base.html" %}
{% block title %}Восстановление пароля завершено{% endblock %}

{% block content %}
  {% with card_header='Восстановление пароля завершено' header_hint='Ваш пароль был сохранен. Теперь вы можете войти.' %}
  {% with add_link_adress={{ login_url }} add_link_text='Войти' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Восстановление пароля завершено{% endblock %}

{% block content %}
  {% with card_header='Восстановление пароля завершено' header_hint='Ваш пароль был сохранен. Теперь вы можете войти.' %}
  {% url 'users:login' as add_link_adress %}
  {% with add_link_text='Войти' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Введите новый пароль{% endblock %}

{% block content %}

{% if validlink %}
  {% with card_header='Введите новый пароль' header_hint='Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.' %}
  {% with text_submit='Изменить мой пароль' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
  {% endwith %}
{% else %}
  {% with card_header='Ошибка' header_hint='Неверная ссылка для восстановления пароля. Возможно, ей уже воспользовались. Пожалуйста, попробуйте восстановить пароль еще раз.' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
{% endif %}

{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Письмо с инструкциями по восстановлению пароля отправлено{% endblock %}

{% block content %}
  {% with card_header='Письмо с инструкциями по восстановлению пароля отправлено' %}
  {% with header_hint='Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.' %}
  {% with header_hint_2='Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.' %}
      {% include 'users/includes/card.html' %} 
  {% endwith %}
  {% endwith %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Востановление пароля{% endblock %}

{% block content %}
  {% with card_header='Востановление пароля' header_hint='Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.' %}
  {% with text_submit='Востановить мой пароль' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
  {% endwith %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}

{% block content %}
  {% with card_header='Зарегистрироваться' %}
  {% with text_submit='Зарегистрироваться' %}
    {% include 'users/includes/card.html' %} 
  {% endwith %}
  {% endwith %}
{% endblock %}